### ISSUE TITLE
neo_perception2 package not found. 

### ISSUE THREAD

**Issue by deepak-anzo** [neobotix/neo_docking2#41]
neo_perception2 not found to record the point cloud .pcd file for the automated docking.

**Comment by padhupradheep** [comment]
Thanks for your interest. 

The neo_perception package is a closed-source package which carries a proprietary license. 

We are still working on the documentation that will showcase the features of the package, in order for the potential customers to decide and have an idea, if they want to acquire the package. 

If I may ask, what's the target use-case? do you by chance already have a Neobotix robot?
